---
  .travis.yml:
    hc_secure: "ATK7yUkRCJU2AzfhUB9YwbxeN3+t4xIoW73puXgVaJp9DmAck29gffAKU48YfzkBMBp1DuTHy6UeiiaDwJYA9GKpyiKOyTtQdIret0gvXAvkEmqRHOgZWPr/oLoHhuveWgtVIYnFTkr4NJj60y6PvZYmNAIOF6a6Zu40QoW6pFw="

